### ISSUE TITLE
inquiry for video

### ISSUE THREAD

**Issue by HU-xiaobai** [yjb6/CS231n-2022#1]
Hello!

你好，我想问问你可以分享一下cs231n 2022的视频嘛？2017的视频感觉和作业在Lecture 11后有明显脱节了（捂脸）

**Comment by yjb6** [comment]
你好！

我也没有找到cs231n的视频呢。b站上最新的cs231n视频应该就是17年了，后面有不少地方是和课件不同步的。我的方法是首先可以尝试自己看课件，如lstm部分我感觉课件上还是不难理解的。此外b站上有Justin在另一所学校开的课程，和cs231n的新版课件比较像，可以参考着看（https://www.bilibili.com/video/BV1TQ4y1B7yx?spm_id_from=333.337.search-card.all.click&vd_source=2f2c5054e297470dcde712d5ac6a7755）。

希望对你有帮助，有问题欢迎继续交流。

**Comment by HU-xiaobai** [comment]
好滴好滴，想问问你也是AI专业的吗？我是爱丁堡AI的master，留个来联系方式不[偷看]？话说这个issue可以关掉不给人看的吧哈哈哈？

**Comment by yjb6** [comment]
我是东南大学计算机大四的，没有系统的学过ai,可以说只是了解到一点皮毛。transformer部分可以尝试去看下李宏毅的课程。
可以加我vx：Promisingman233
